#!/bin/sh
echo "=========== pre commit ==========="

# 1. Checkstyle 확인

echo "▶ Running Checkstyle..."
./gradlew checkstyleMain
if [ $? -ne 0 ]; then
    echo "▷ Checkstyle violations found!!"
    echo "=========== pre commit : FAILED ==========="
    exit 1
fi
echo "▷ Checkstyle Done!"

echo "=========== pre commit : SUCCEED ==========="
exit 0